export const teams = [
  {
    name: "Jakub Buciuto",
    username: "MrJacob12",
    owner: true,
    github: "https://github.com/MrJacob12",
    linkedin: "https://www.linkedin.com/in/jakub-buciuto-4972bb21b/",
    avatar: "https://avatars.githubusercontent.com/u/46843555?v=4",
    tags: ["python", "react", "rust", "typescript"],
  },
  {
    name: "Bartłomiej Kudzia",
    username: "QQLKAA",
    github: "https://github.com/QQLKAA",
    linkedin: "",
    avatar: "https://avatars.githubusercontent.com/u/27441333?v=4",
    tags: ["c", "c-plus-plus", "python", "react", "typescript"],
  },
  {
    name: "Kacper Kostera",
    username: "Skimper",
    github: "https://github.com/Skimper",
    linkedin: "",
    avatar: "https://avatars.githubusercontent.com/u/42150605?v=4",
    tags: ["c-sharp", "java", "react", "typescript"],
  },
  {
    name: "Marcel Bełtowski",
    username: "mbeltowski",
    github: "https://github.com/mbeltowski",
    linkedin: "https://www.linkedin.com/in/marcel-be%C5%82towski-38ab9626a/",
    avatar: "https://avatars.githubusercontent.com/u/49125323?v=4",
    tags: ["typescript", "react", "lua"],
  },
];
